name: flutter_sapo_one
description: flutter test sapo one
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.4.0
  equatable: ^2.0.7
  firebase_core: 3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: 8.0.3
  intl: ^0.19.0
  so_ui:
    path: packages/core/so_ui
  so_utils:
    path: packages/core/so_utils
  so_verification_data:
    path: packages/features/so_verification_data
  so_verification_domain:
    path: packages/features/so_verification_domain

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
