// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKxKnVTjFmPiQAPgnnWmCFS4yYL-72R6I',
    appId: '1:235754273229:web:43e772b021270ab3dbac84',
    messagingSenderId: '235754273229',
    projectId: 'sapo-one',
    authDomain: 'sapo-one.firebaseapp.com',
    storageBucket: 'sapo-one.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPBPyYZgXBsoI0eyu9xnltb1Yi6a42OYk',
    appId: '1:235754273229:android:55786be0fd06e13edbac84',
    messagingSenderId: '235754273229',
    projectId: 'sapo-one',
    storageBucket: 'sapo-one.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ND_MyegZn9AKlTZC_wZXq0uAoS0cb-s',
    appId: '1:235754273229:ios:c58bf31188266034dbac84',
    messagingSenderId: '235754273229',
    projectId: 'sapo-one',
    storageBucket: 'sapo-one.firebasestorage.app',
    iosBundleId: 'com.sapo.one.flutter-sapo-one',
  );

}